### ISSUE TITLE
Casbin v3

### ISSUE THREAD

**Issue by nodece** [casbin/enhancements#2]
The following is aiming for Casbin v3:

- improve the performance of enforce - https://github.com/casbin/casbin/issues/516, https://github.com/casbin/casbin/issues/546, https://github.com/casbin/casbin/issues/439
- improve consistence between multiple Casbin enforcer instances - [distributed-plugin](https://github.com/casbin/enhancements/tree/master/docs/distributed-plugin)
- improve log, we will record the log of manage + enforce
- metric support.  https://github.com/casbin/casbin/issues/540

we  release criteria to progress from beta > GA.

**Comment by hsluoyz** [comment]
Closed as stale.
